name: Gen API and Create Release

on:
  workflow_dispatch:
# TODO handle staging and production envs
    inputs:
      target_branch:
        description: 'Target environment'
        required: false
        default: 'main'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - name: Initialize git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_GITHUB_TOKEN }}

      - name: Pull API swagger.json
        run: npm run api:pull
        env:
          SWAGGER_JSON_PATH: https://pixwayid.stg.pixway.io/sdk-json

      - name: Generate API from swagger
        run: npm run api:gen
        env:
          SWAGGER_JSON_PATH: https://pixwayid.stg.pixway.io/sdk-json

      - name: Create Pre Release
        if: "${{ github.event.inputs.target_branch != 'main' }}"
        run: npm run release -- --prerelease

      - name: Get package version
        uses: bbonkr/get-version-action@v1.0.4
        id: get_version
        with:
          project: "./package.json"

      - name: Pushing version ${{ steps.get_version.outputs.version }} on ${GITHUB_REF##*/} with tags
        run: git push --follow-tags origin ${GITHUB_REF##*/}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.get_version.outputs.version }}
          message: '(chore): PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }} version ${{ steps.get_version.outputs.version }}'
